### ISSUE TITLE
onPress works after delay on Android

### ISSUE THREAD

**Issue by ivan-kalinin** [computerjazz/react-native-draggable-flatlist#120] opened 2020-01-14 11:10 UTC
`
"react-native-draggable-flatlist": "2.0.10",
"react-native": "0.61.5",
`

Simple instance. 
```javascript
<DraggableFlatList
   data={this.props.words}
   renderItem={this.renderItem}
   ...
/>
````

Any touchable components inside of **renderItem** component works only after some press delay. Only click is not working, it needs press and wait a bit. Looks like it's about 100-200 ms. iOS works perfectly, problem is only on Adroid.

**Comment by johandk89** [comment] 2020-01-15 08:21
I have the same issue

**Comment by csath** [comment] 2020-01-16 05:18
Have the same issue

**Comment by gyurui** [comment] 2020-01-16 13:04
I have the same problem

**Comment by computerjazz** [comment] 2020-01-16 22:02
likely an issue with RNGH: https://github.com/software-mansion/react-native-gesture-handler/issues/920

**Comment by computerjazz** [comment] 2020-01-16 22:09
also related: https://github.com/software-mansion/react-native-gesture-handler/issues/745
although that has been closed

**Comment by curiousdustin** [comment] 2020-01-17 15:55
Just to add clarification for others:

Using `onPressOut` as mentioned by @gyurui mentioned is not great because it is triggered in cases you wouldn't want such as:

- Attempting to cancel a press by moving out of the hit area and releasing
- Intending to scroll a list instead of actually press a button contained in the list

**Comment by johnnyrockfort** [comment] 2020-01-20 13:27
The same here for us... Any idea when this will be fixed?

**Comment by computerjazz** [comment] 2020-01-20 17:04
As this appears to be an upstream bug, I encourage you to help find a fix on the RNGH repo.

**Comment by computerjazz** [comment] 2020-01-23 17:33
Can someone try using the Touchables exported from react-native-gesture-handler and see if that solves the issue?

**Comment by curiousdustin** [comment] 2020-01-23 17:43
I tried this and ended up with issues with nested touchables. https://github.com/computerjazz/react-native-draggable-flatlist/issues/99#issuecomment-573807397

This seems like a common scenario as you typically want to be able to touch the entire list item, but then also have buttons within the item.

**Comment by computerjazz** [comment] 2020-01-23 17:54
Hm yeah, RNGH + Touchables has been an issue for a while 😕
Another related issue on a package created by the author or RNGH, in which he responds:
https://github.com/osdnk/react-native-reanimated-bottom-sheet/issues/16#issuecomment-475989947

Unfortunately the solution there (disabling tap) won't work for react-native-draggable-flatlist as we rely on the tap to calculate offsets.

**Comment by theashguy** [comment] 2020-01-28 00:13
Hi there all!

@computerjazz in response to your question-- I can confirm that applying the `react-native-gesture-handler` touchables works well to solve this one. In my case I'm applying them as an alternative component based on the platform to my ListItem as follows (this example is incomplete obviously):

```
import {
  Platform,
  TouchableHighlight
} from 'react-native';
import {
  FlatList,
  TouchableNativeFeedback
} from 'react-native-gesture-handler';

<FlatList
    ...props...
    renderItem={({ item }) => (
        <ListItem
            ...props...
            Component={Platform.select({
                android: TouchableNativeFeedback as any,
                default: TouchableHighlight
            })}
            onPress={() =>
                // Do your thing
            }
         />
    )}
/>
```

Likely should still be looked into as a bug, but this workaround is fully functional and doesn't seem to have any negative effects. Enjoy!

**Comment by ivan-kalinin** [comment] 2020-01-31 10:25
> Hi there all / @computerjazz!
> 
> I can confirm that applying the `react-native-gesture-handler` touchables works well to solve this one. In my case I'm applying them as an alternative component based on the platform to my ListItem as follows (this example is incomplete obviously):
> 
> ```
> import {
>   Platform,
>   TouchableHighlight
> } from 'react-native';
> 
> import {
>   FlatList,
>   TouchableNativeFeedback
> } from 'react-native-gesture-handler';
> 
> <FlatList
>     ...props...
>     renderItem={({ item }) => (
>         <ListItem
>             ...props...
>             Component={Platform.select({
>                 android: TouchableNativeFeedback as any,
>                 default: TouchableHighlight
>             })}
>             onPress={() =>
>                 // Do your thing
>             }
>          />
>     )}
> />
> ```
> 
> Likely should still be looked into as a bug, but this workaround is fully functional and doesn't seem to have any negative effects. Enjoy!

I've used workaround with TouchableNativeFeedback for now as well.

**Comment by deiucanta** [comment] 2020-02-05 18:19
@computerjazz Are you sure this is a RNGH bug and not something related to the way you setup the tap/pan handlers?

I'm thinking of `react-navigation` which uses RNGH and there are no issues with `react-native` touchables inside the screens.

**Comment by computerjazz** [comment] 2020-02-05 18:24
I think the issue is specifically with the `TapGestureHandler` wrapper --  I'm not sure react-navigation needs this

**Comment by curiousdustin** [comment] 2020-02-05 18:28
That is the same conclusion I came to.

RNGH recommends using their version of the Touchables. However, doing that results in alternate bugs, such as the inability to nest Touchables. (https://github.com/computerjazz/react-native-draggable-flatlist/issues/99#issuecomment-573807397)

If you don't need to nest them, this may work for you.

**Comment by deiucanta** [comment] 2020-02-05 18:36
That makes sense. Any way to avoid using `TapGestureHandler` in `react-native-draggable-flatlist`?

**Comment by computerjazz** [comment] 2020-02-05 19:09
Hm it _might_ be possible to use `PanGestureHandler` for everything, since we don't technically need to calculate any offsets etc until the user actually begins panning., It would require some rewriting but at this point that seems like a decent option.

**Comment by deiucanta** [comment] 2020-02-10 18:11
@computerjazz what if you set `minDist` to 0?

**Comment by computerjazz** [comment] 2020-02-10 18:19
@deiucanta  I'm not sure I follow how that would help -- explain please?

Update on removing TapGestureHandler -- I realized we don't actually need the offset info until we pan, as the cell itself can provide its "pre-pan" offset. I removed the TapGestureHandlers and pushed the change to master, but will need to test thoroughly before I'm convinced it's a bug-free fix.

**Comment by deiucanta** [comment] 2020-02-10 18:26
@computerjazz if you set `minDist` to 0 on the PanGestureHandler I think you will be able to get the offset right away, without having to move the pointer.

**Comment by computerjazz** [comment] 2020-02-10 18:30
ah I see. That may work, although I'm worried that may interfere with scroll by capturing the gesture before the scrollview has a chance to grab it.

**Comment by computerjazz** [comment] 2020-02-10 19:01
I dropped the latest update with TapGestureHandler removed into a snack if folks want to try to break things: https://snack.expo.io/BJ!3zmkXL

I have tested on android and verified it fixes the onPress issue.

**Comment by computerjazz** [comment] 2020-02-16 04:34
Removed `TapGestureHandler` in `2.3.0`, please let me know if the onPress issue is fixed.

**Comment by ivan-kalinin** [comment] 2020-02-16 07:56
Updated to `2.3.0`. Seems it works 🚀

**Comment by ivan-kalinin** [comment] 2020-02-16 08:33
@computerjazz 
At the same time I noticed some time ago opened issue about nesting this draggable-flatlist was referred on this ticket and the new update doesn't solve it. 

The problem is when draggable-flatlist lays inside of scrollview (in my case keyboard-aware-scroll-view), the outer scrollview doesn't trigger the scroll action above draggable-flatlist, but trigger it above usual flatlist. 

```javascript
<ScrollView scrollEnabled ...>  
   <View ... /> // some content
   <Flatlist scrollEnabled={false} ... /> //  <-CAN capture outer scroll
   <DraggableFlatList scrollEnabled={false} ... /> //  <-CANNOT capture outer scroll
<ScrollView/>
```

I mean I do not need scroll nested draggable-flatlist or flatlist itself, I need to scroll all content as one per page. But it's still stuck above draggable-flatlist. Both platforms.

**Comment by computerjazz** [comment] 2020-02-16 16:37
@ivan-kalinin the nested scrollview issue is not related to this.
There are a few related issues, please move to the appropriate one:
https://github.com/computerjazz/react-native-draggable-flatlist/issues/15
https://github.com/computerjazz/react-native-draggable-flatlist/issues/106

**Comment by ivan-kalinin** [comment] 2020-02-17 16:51
@computerjazz ok, thanks a lot! I think we're ready to close this ticket so.

**Closed** 2020-02-17 17:21 UTC
