### ISSUE TITLE
Can not do drag after updating the library.

### ISSUE THREAD

**Issue by Harsh2402** [computerjazz/react-native-draggable-flatlist#131] opened 2020-01-23 06:11 UTC
I am not able to drag my items after updating the library.

**Comment by computerjazz** [comment] 2020-01-23 17:09
Did you follow all instructions for adding reanimated and react-native-gesture-handler in the readme?

**Comment by computerjazz** [comment] 2020-01-24 18:16
there was also an android bug fixed in 2.1.2, can you upgrade and see if your issue is fixed?

**Comment by StevenBlack** [comment] 2020-01-25 03:30
Hi Daniel @computerjazz, same issue here.  

I was on `1.1.7`, upgraded to latest official release, then all the way to `2.1.1`.  I'm using Expo, running iOS only.  I'm on React `16.8.3` which is a little different than what you have.

Reverting back to 1.1.7, and all is well.  I'm actually happy there, but I hate having a critical component lagging behind for reasons I haven't grokked.   

Do you have any insight to share?  A quick button to button?  There's no useful information on the [releases page](https://github.com/computerjazz/react-native-draggable-flatlist/releases), and scanning the first few [commits pages], nothing jumps out at me.

It's got to be something simple...

**Comment by computerjazz** [comment] 2020-01-26 17:25
@StevenBlack there was a bug in `2.1.1`, can you try `2.1.2`?

Which version of expo are you on? I recommend using 36+ as there are some critical perf improvements in reanimated included in that release.

**Comment by StevenBlack** [comment] 2020-01-26 20:21
Thanks for the suggestion Daniel @computerjazz.  Still no dragging using version`2.1.2`.

We're on Expo version 33, still.  Maybe that's the cause.  Switching to 36 is a pain point, given our deployed base is using the app 24-7, or nearly so.

One thing that's not clear in the context of Expo and `react-native-draggable-flatlist`:  The docs say to follow the instructions for installing [`reanimated`](https://github.com/kmagiera/react-native-reanimated), which calls for `react-native link react-native-reanimated`.  No `react-native` cli ships with Expo; it's just never part of the deal, with Expo.  So I'm wary of going down that route, it's just feels hacky.  Not that Expo isn't hacky enough, to begin with.

I'll revert back to `1.1.7` again.  It's just not clear what `2.1.2` buys us, other than the comfort of keeping-up with version numbers.  I wish `react-native-draggable-flatlist` had a change log, or verbose releases, not necessarily for patch releases, but for major release increments, certainly.

Thank you for your help on this, Daniel.  I'm good.  I'm just sorry to be left behind, with no notion why that's the case, what features we're missing.

**Comment by computerjazz** [comment] 2020-01-26 21:19
Sorry to hear you're still having trouble. reanimated and react-native-gesture-handler are included with expo, so you shouldn't need to do any additional linking or installation steps. 33 is a few versions back, but I just tested with this snack and it seems to work, so I'm stumped: https://snack.expo.io/@computerjazz/swipetodelete-pkg

v2 introduces major performance improvements (and lots of other code simplifications), especially on android, but you won't see some of those if you're not on expo 36. If you're not noticing any choppiness then it makes sense to stick with what's working.

**Comment by StevenBlack** [comment] 2020-01-26 21:23
Thanks Daniel @computerjazz!  That's interesting.

I'll try a simple implementation, from scratch, and see where that leads.

I appreciate you're support here.  Very much.

**Comment by rodgomesc** [comment] 2020-02-01 20:56
same problem

**Comment by rassemdev** [comment] 2020-03-11 01:40
same problem here..

**Comment by phillipkey** [comment] 2020-03-16 20:47
On the latest version, it only works on ios. For android, i cannot get any animation.

**Comment by fredrivett** [comment] 2020-04-28 09:19
Also not working for me, using the example from the `README` with Expo, is it working for anyone?

**Comment by NickAlvesX** [comment] 2020-05-06 20:39
+1

**Comment by fredrivett** [comment] 2020-05-24 12:40
Quick update from my end, the example is working for me when I implement it in my own app, either I was a dumbass before (most likely) or something was updated that fixed an issue.

It's working beautifully, thanks @computerjazz 🙌🏼

**Comment by SimpleCreations** [comment] 2020-07-21 14:28
Same issue. Updated from 1.x to 2.3.6. The items are not moving anymore. When I touch the drag handle, the list doesn't scroll, indicating that the item is supposed to be dragged, but it stays in the same place.
I'm using RN 0.62.2 on Android (Hermes enabled), `react-native-reanimated@1.9.0`, `react-native-gesture-handler@1.6.1`.

Two messages keep appearing in the console:
```
## attempt to call drag() on hovering component
## Can't set multiple active items
```

**Comment by computerjazz** [comment] 2020-07-21 16:44
@SimpleCreations I've been using this snack to test DraggableFlatlist functionality -- can you modify it and repro your issue? https://snack.expo.io/@computerjazz/swipetodelete-pkg

**Closed** 2021-11-12 21:30 UTC
