### ISSUE TITLE
Having conflicts with parent ScrollView

### ISSUE THREAD

**Issue by bcklup** [computerjazz/react-native-draggable-flatlist#184] opened 2020-05-18 23:59 UTC
**Describe the bug**
When you nest this component inside a ScrollView, dragging around the area of this component won't scroll the ScrollView.

**To Reproduce**
Have a DraggableFlatlist component inside a View with the ScrollView as it's parent (ScrollView -> View -> DraggableFlatList). When you try to scroll the ScrollView around the region of the DraggableFlatList it will not respond.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: iOS & Android
 - React Native or Expo version: 0.62.1
 - Reanimated version: 1.8.0
 - React Native Gesture Handler version: 1.6.1

**Additional context**
This used to work on the pre-RN 0.60 versions of this component so I'm confused why the existing functionality no longer works.

**Comment by computerjazz** [comment] 2020-05-26 22:02
Duplicate of https://github.com/computerjazz/react-native-draggable-flatlist/issues/106
But keeping this one as it has the issue template filled out

**Comment by user14045** [comment] 2020-06-03 01:56
any update on this? This lib is great. And it gonna be very great if this issue solved. I found another library, https://github.com/thomasrovayaz/react-native-draggable-dynamic-flatlist. I can scroll inside the scrollview. But, the drag-drop not working

**Comment by ralppppy** [comment] 2020-06-14 13:23
Is there any update on this? I broke my layout because of this issue.  I've already tried react-native-draggable-dynamic-flatlist but it is not as good as this. I think the list should be scrollable when you are not dragging, and when you start dragging that's the time to disable scroll.

**Comment by computerjazz** [comment] 2020-06-15 16:38
The underlying issue is that a `react-native-gesture-handler` `PanGestureHandler` captures the gesture from the parent ScrollView. I haven't had time to investigate and it'd be great if someone else could.

**Comment by JosephCon1998** [comment] 2020-06-16 19:29
I'm using a workaround that works but its probably not ideal and might not work for everyones use case.

So anything I want to be able to scroll as well as drag and I am putting inside the ListHeaderComponent for the FlatList

```javascript
<DraggableFlatList
        ListHeaderComponent={() => (
           <>
              // Every component above the draggable list I want to scroll
           </>
        )}
        renderItem={({ item, index, drag, isActive }) => (
          <MyDraggableComponent />
        )}
       ListFooterComponent={() => (
           <>
              // Every component below the draggable list i want to scroll
           </>
       )}
/>
```

This works for me with how my app is using the draggable list, but again its not ideal for everybody but hope it helps someone.

**Comment by rednebmas** [comment] 2020-06-17 18:11
My cells have a "drag handle" and my workaround for this issue was to add a `dragHitSlop` property to `DraggableFlatList` and pass that down to the `PanGestureHandler` in render.

**Comment by bill-pairaktaridis** [comment] 2020-06-25 13:35
> My cells have a "drag handle" and my workaround for this issue was to add a `dragHitSlop` property to `DraggableFlatList` and pass that down to the `PanGestureHandler` as [`hitSlop`](https://docs.swmansion.com/react-native-gesture-handler/docs/handler-common.html#hitslop) in render .

Could you elaborate on that?

**Comment by ds-karpov** [comment] 2020-08-09 09:35
> My cells have a "drag handle" and my workaround for this issue was to add a `dragHitSlop` property to `DraggableFlatList` and pass that down to the `PanGestureHandler` as [`hitSlop`](https://docs.swmansion.com/react-native-gesture-handler/docs/handler-common.html#hitslop) in render .

Dear rednebmas, could you please add detailed instruction of your solution? 
Thanks

**Comment by ioveracker** [comment] 2020-08-21 08:21
I've found a workaround. Set the `activationDistance` prop (on `DraggableFlatList`) to a value greater than zero. In my testing, even `1` is enough to allow swiping horizontally within the parent scroll view without interfering with drag and drop functionality.

**Comment by mtalhagaoglu** [comment] 2020-09-06 11:44
hi. i have the same bug. when there is too much item for screen height it hiding. i can't scroll to bottom. i tried activationDistance but if i do that i am not able to drag items.

**Comment by JairZijp** [comment] 2020-09-23 09:55
Yeah same problem as @mtalhagaoglu here. When I add activationDistance the scrolling works but the dragging doesn't

**Comment by mtalhagaoglu** [comment] 2020-09-23 10:15
> Yeah same problem as @mtalhagaoglu here. When I add activationDistance the scrolling works but the dragging doesn't

my problem caused because parent scrollview. when i remove that it starts to work as should be.

**Comment by Svarto** [comment] 2020-10-13 08:44
@bill-pairaktaridis @ds-karpov created pull requests adding in hitSlop parameter to allow for @rednebmas solution. #232 #231 

This allows for controlling what part of the DraggableFlatlist responds to gesture events. Meaning if you disable it, the parent ScrollView will take precedence and continue to work. I have solved it by creating a handle that activates with a toggle, if the toggle is false then the parent ScrollView scrolls normally, if it is true then the drag handle appears and allows for dragging the item, while the rest of the DraggableFlatlist item still responds to the parent ScrollView (because hitSlop is set to ignore gesture events on all parts of the item except the drag handle).

```
      <DraggableFlatList
        data={data}
        dragItemOverflow={true}
        renderItem={renderItem}
        dragHitSlop={
          active ? { right: -(width * 0.95 - 20) } : { right: -width }
        }
        keyExtractor={(item, index) => `draggable-item-${item.order}`}
        }}
      />
```

**Comment by creambyemute** [comment] 2020-10-28 19:06
Another option for me was to use the following approach:

Update libraries:
* RN-Draggable-Flatlist 2.3.3 --> 2.4.0
* RN-Gesture-Handler to 1.6.1 --> 1.8.0
* RN-Reanimated to 1.9 --> 1.13.1
* RN-Screens to 2.8 --> 2.11.0 (not sure if related)
* RN-Safe-Area-Context to 3.0.8 --> 3.1.8 (not sure if related)

Together with the following inside ScrollViews.
```javascript
<DraggableFlatList
                            style={{
                                maxHeight:
                                    Platform.OS === "ios"
                                        ? this.props.rootStore.commonStore.windowHeight / 1.15
                                        : this.props.rootStore.commonStore.windowHeight / 1.17
                            }}
```

**Comment by pedro-lb** [comment] 2020-12-09 15:41
> ```js
> ListHeaderComponent
> ```

This works fine and is by far the most straightforward solution out there, albeit not so clean

**Comment by pedro-lb** [comment] 2020-12-09 15:42
> I'm using a workaround that works but its probably not ideal and might not work for everyones use case.
> 
> So anything I want to be able to scroll as well as drag and I am putting inside the ListHeaderComponent for the FlatList
> 
> ```js
> <DraggableFlatList
>         ListHeaderComponent={() => (
>            <>
>               // Every component above the draggable list I want to scroll
>            </>
>         )}
>         renderItem={({ item, index, drag, isActive }) => (
>           <MyDraggableComponent />
>         )}
>        ListFooterComponent={() => (
>            <>
>               // Every component below the draggable list i want to scroll
>            </>
>        )}
> />
> ```
> 
> This works for me with how my app is using the draggable list, but again its not ideal for everybody but hope it helps someone.
> 
> Also make sure to get rid of the parent scrollview

This works fine and is by far the most straightforward solution out there, albeit not so clean

**Comment by sanduluca** [comment] 2021-01-26 17:15
> I've found a workaround, but it seems to sometimes block vertical scrolling. Set the `activationDistance` prop (on `DraggableFlatList`) to a value greater than zero. In my testing, even `1` is enough to allow swiping horizontally within the parent scroll view without interfering with drag and drop functionality, but `10` provides more consistent scrolling within the `DraggableFlatList`.

I have a `ScrollView` with some content inside. It also has a horizontal `DraggableFlatList`. The issue was that I wasn't able to scroll vertically when the touch started from the `DraggableFlatList` area. Setting `activationDistance={10}` solves the problem with scrolling. 
I want to mention that the dragging is also working fine.
This is basically all I have:
```js
<ScrollView>
// some content goes here (Views, Text, Images, Inputs)
<DraggableFlatList
          data={this.props.images}
          keyExtractor={(item) => item}
          renderItem={this.renderGalleryItem}
          onDragEnd={({ data }) => this.onDragEnd(data)}
          ItemSeparatorComponent={this.renderItemSeparator}
          ListHeaderComponent={this.renderImagePicker}
          horizontal={true}
          activationDistance={10}
        />
// some content goes here (Views, Text, Images, Inputs)
<ScrollView/>
```
Its a photo carousel 
![image](https://user-images.githubusercontent.com/56228534/105879190-89a28100-600a-11eb-9f8a-ecba9acc31a9.png)

**Comment by midimurphdesigns** [comment] 2021-01-29 21:54
if my list gets too long, I need to have vertical scroll. None of the solutions provided are working for me. Any other insight?

**Comment by daybreaker** [comment] 2021-02-08 05:12
Same, would really like a solution as this is one of the only drag and drop libraries I've found that doesn't require the elements to have a fixed height.

**Comment by Donhv** [comment] 2021-06-08 16:11
Is there any update on this? I broke my layout because of this issue. :(((

**Comment by Daniel-Griffiths** [comment] 2021-06-14 12:12
> @bill-pairaktaridis @ds-karpov created pull requests adding in hitSlop parameter to allow for @rednebmas solution. #232 #231
> 
> This allows for controlling what part of the DraggableFlatlist responds to gesture events. Meaning if you disable it, the parent ScrollView will take precedence and continue to work. I have solved it by creating a handle that activates with a toggle, if the toggle is false then the parent ScrollView scrolls normally, if it is true then the drag handle appears and allows for dragging the item, while the rest of the DraggableFlatlist item still responds to the parent ScrollView (because hitSlop is set to ignore gesture events on all parts of the item except the drag handle).
> 
> ```
>       <DraggableFlatList
>         data={data}
>         dragItemOverflow={true}
>         renderItem={renderItem}
>         dragHitSlop={
>           active ? { right: -(width * 0.95 - 20) } : { right: -width }
>         }
>         keyExtractor={(item, index) => `draggable-item-${item.order}`}
>         }}
>       />
> ```

This answer worked for me, thank you!

**Comment by samuelndm** [comment] 2021-06-25 03:31
> dragHitSlop={
>           active ? { right: -(width * 0.95 - 20) } : { right: -width }
>         }

 @Svarto  would you help me please? Where did this active and width variables come from?

**Comment by ashutosh-stha23** [comment] 2022-01-22 18:44
> dragHitSlop={
>           active ? { right: -(width * 0.95 - 20) } : { right: -width }
>         }

how are you toggling  active to be true or false?

**Comment by Svarto** [comment] 2022-01-22 19:32
> > dragHitSlop={
> >           active ? { right: -(width * 0.95 - 20) } : { right: -width }
> >         }
> 
> how are you toggling  active to be true or false?
> 

Just a standard useState tied to a button ("Edit order")

**Comment by ashutosh-stha23** [comment] 2022-01-23 04:23
> > > dragHitSlop={
> > > active ? { right: -(width * 0.95 - 20) } : { right: -width }
> > > }
> > 
> > 
> > how are you toggling  active to be true or false?
> 
> Just a standard useState tied to a button ("Edit order")

Thanks. I don't have any button for that.  So thought could we do it with onDragBegin and onDragEnd. It was not working properly.

**Comment by Svarto** [comment] 2022-01-23 06:41
> > > > dragHitSlop={
> > > > active ? { right: -(width * 0.95 - 20) } : { right: -width }
> > > > }
> > > 
> > > 
> > > how are you toggling  active to be true or false?
> > 
> > Just a standard useState tied to a button ("Edit order")
> 
> Thanks. I don't have any button for that.  So thought could we do it with onDragBegin and onDragEnd. It was not working properly. 

Aha, did you try using a useRef instead of useState?

**Comment by MaheshGawhane11** [comment] 2022-01-27 06:36
> > I'm using a workaround that works but its probably not ideal and might not work for everyones use case.
> > So anything I want to be able to scroll as well as drag and I am putting inside the ListHeaderComponent for the FlatList
> > ```js
> > <DraggableFlatList
> >         ListHeaderComponent={() => (
> >            <>
> >               // Every component above the draggable list I want to scroll
> >            </>
> >         )}
> >         renderItem={({ item, index, drag, isActive }) => (
> >           <MyDraggableComponent />
> >         )}
> >        ListFooterComponent={() => (
> >            <>
> >               // Every component below the draggable list i want to scroll
> >            </>
> >        )}
> > />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This works for me with how my app is using the draggable list, but again its not ideal for everybody but hope it helps someone.
> > Also make sure to get rid of the parent scrollview
> 
> This works fine and is by far the most straightforward solution out there, albeit not so clean

Thank you! It works for me.

**Comment by computerjazz** [comment] 2022-04-13 23:19
Nesting support added in `3.1.0`: https://github.com/computerjazz/react-native-draggable-flatlist/releases/tag/v3.1.0

**Closed by computerjazz** 2022-04-13 23:19 UTC

**Comment by DimaSydorko** [comment] 2022-05-08 11:14
<GestureHandlerRootView style={{ flex: 1, backgroundColor: 'seashell' }}>

**Comment by gabriellend** [comment] 2024-05-01 22:34
The nestable support wasn't working for my use case (Parent FlatList rendering items with draggable lists inside), it was causing performance issues because I couldn't set windowSize, initialNumToRender, etc. on the FlatList when it was inside the NestableScrollView. Moving it further down the tree didn't work either. Maybe there was a way to make it work but I couldn't figure it out. What I did was use a parent FlatList and just use DraggableFlats inside each item, and setting activationDistance={40} seemed to do the trick for me. Just leaving this here for anyone who stumbles upon this thread!
