### ISSUE TITLE
android pull to refresh not work

### ISSUE THREAD

**Issue by gdoudeng** [computerjazz/react-native-draggable-flatlist#296] opened 2021-06-18 03:05 UTC
*This package has external dependencies of [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) and [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) which must be installed separately. Before opening an issue related to animations or gestures please verify that you have completed ALL installation steps, including the [changes to MainActivity.](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android)*

**Describe the bug**

android pull to refresh not work,but ios work

```js
<DraggableFlatList
              onRef={(flatList) => (this.homeList = flatList)}
              style={styles.mt10}
              data={items}
              extraData={isDelete}
              renderItem={this._renderItem}
              ItemSeparatorComponent={this._separator}
              ListFooterComponent={this._footer}
              ListEmptyComponent={this._listEmpty}
              keyExtractor={item => item.id}
              onEndReachedThreshold={0.1}
              onEndReached={this._loadMoreData}
              keyboardDismissMode="on-drag"
              onScrollOffsetChange={this._onHomeListScroll}
              onDragEnd={this.handleDragEnd}
              refreshControl={
                <RefreshControl
                    onRefresh={this._refreshData}
                    refreshing={isRefreshing}
                />
              }
          />
```

**To Reproduce**
Link a snack if possible.

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform:
 - React Native or Expo version:
 - Reanimated version:
 - React Native Gesture Handler version:

**Additional context**

**Comment by gdoudeng** [comment] 2021-06-18 06:45
This problem is serious...

**Comment by computerjazz** [comment] 2021-06-18 19:33
Closing as this is a duplicate of #135

**Closed by computerjazz** 2021-06-18 19:33 UTC
