### ISSUE TITLE
Is it impossible to exchange items between FlatList?

### ISSUE THREAD

**Issue by NotRayor** [computerjazz/react-native-draggable-flatlist#419] opened 2022-10-20 06:07 UTC
```

import { NestableScrollContainer, NestableDraggableFlatList } from "react-native-draggable-flatlist"

...

  const [data1, setData1] = useState(initialData1);
  const [data2, setData2] = useState(initialData2);
  const [data3, setData3] = useState(initialData3);

  return (
    <NestableScrollContainer>
      <Header text='List 1' />
      <NestableDraggableFlatList
        data={data1}
        renderItem={renderItem}
        keyExtractor={keyExtractor}
        onDragEnd={({ data }) => setData1(data)}
      />
      <Header text='List 2' />
      <NestableDraggableFlatList
        data={data2}
        renderItem={renderItem}
        keyExtractor={keyExtractor}
        onDragEnd={({ data }) => setData2(data)}
      />
      <Header text='List 3' />
      <NestableDraggableFlatList
        data={data3}
        renderItem={renderItem}
        keyExtractor={keyExtractor}
        onDragEnd={({ data }) => setData3(data)}
      />
    </NestableScrollContainer>
  )
```

I want to implement the function of moving items by dragging and dropping between flatLists
Is there any way?

like this : 

![resize](https://raw.githubusercontent.com/lesniakania/react-native-draggable-board/master/drag-and-drop-demo.gif)

**Comment by adam-lynch** [comment] 2022-10-26 08:25
Looks like a duplicate of #404 maybe

**Comment by computerjazz** [comment] 2022-11-20 03:07
No, not possible

**Closed by computerjazz** 2022-11-20 03:07 UTC
