### ISSUE TITLE
ReferenceError: Property '_setGlobalConsole' doesn't exist

### ISSUE THREAD

**Issue by Yandamuri** [computerjazz/react-native-draggable-flatlist#259] opened 2021-01-22 11:05 UTC
**Describe the bug**
As soon as I ran app got following error

> Requiring module "..\gromainui\node_modules\react-native-draggable-flatlist\lib\index.js", which threw an exception: ReferenceError: Property '_setGlobalConsole' doesn't exist, js engine: hermes

**To Reproduce**
Just implement the basic Draggable Flatlist. then you can see this error

**Platform & Dependencies**
 - Platform: android
 - React Native version: 0.63.2
 - Reanimated version: 2.0.0-rc.2
 - React Native Gesture Handler version: 1.9.0

**Additional context**
Please note that for the first time when I run the app, everything was fine. After working for some time got the error suddenly.

**Comment by computerjazz** [comment] 2021-01-22 18:59
looks like a bug with hermes/reanimated: https://github.com/facebook/hermes/issues/444

**Comment by Yandamuri** [comment] 2021-01-25 05:50
@computerjazz Thank you for your response. I have gone through following issues,

[facebook/hermes/issues/444](https://github.com/facebook/hermes/issues/444)

[react-native-reanimated/issues/1640](https://github.com/software-mansion/react-native-reanimated/issues/1640)

And realized that many people are facing this issue because of `react-native-reanimated` and there is no fix as of now. Is there any alternative or is it possible to use `react-native-draggable-flatlist` without depending on `react-native-reanimated`?

Even though it's  a great package unable to use it because of mentioned error. Please suggest any alternative.

**Comment by computerjazz** [comment] 2021-01-25 17:14
there is no way to use this package without reanimated.

**Comment by computerjazz** [comment] 2021-01-26 23:02
closing as the issue is outside the scope of this package

**Closed by computerjazz** 2021-01-26 23:02 UTC

**Comment by Yandamuri** [comment] 2021-01-27 06:25
I have resolved the error by following this thread,

https://github.com/software-mansion/react-native-reanimated/issues/1640
